apiVersion: apps/v1
kind: Deployment
metadata:
  name: aiservice
  labels:
    app: aiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aiservice
  template:
    metadata:
      labels:
        app: aiservice
        'sidecar.istio.io/inject': "true"
    spec:
      containers:
        - name: aiservice
          image: project15acr.azurecr.io/aiservice:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
          env:
            - name: SPRING_PROFILES_ACTIVE  
              value: "docker"
            - name: SPRING_GPT_BASE_URL
              value: https://api.openai.com/v1
            - name: SPRING_GPT_IMAGE_URL
              value: https://api.openai.com/v1
            - name: SPRING_GPT_MODEL
              value: gpt-4o-mini
            - name: SPRING_GPT_IMAGE_MODEL
              value: dall-e-3
            - name: SPRING_GPT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key-secret
                  key: api_key
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8084
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5