apiVersion: apps/v1
kind: Deployment
metadata:
  name: writing
  labels:
    app: writing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writing
  template:
    metadata:
      labels:
        app: writing
        'sidecar.istio.io/inject': "true"
    spec:
      containers:
        - name: writing
          image: project15acr.azurecr.io/writing:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8086
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5